/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent {
  'mission' : string,
  'description' : string,
  'vision' : string,
}
export type AdminResult = { 'ok' : null } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export interface BlogPost {
  'id' : Id,
  'title' : string,
  'content' : string,
  'date' : Timestamp,
  'published' : boolean,
  'slug' : string,
  'tags' : Array<string>,
  'author' : string,
  'summary' : string,
}
export interface BlogPostInput {
  'title' : string,
  'content' : string,
  'date' : Timestamp,
  'published' : boolean,
  'slug' : string,
  'tags' : Array<string>,
  'author' : string,
  'summary' : string,
}
export interface Client {
  'id' : Id,
  'websiteUrl' : Url,
  'sortOrder' : bigint,
  'name' : string,
  'logoUrl' : Url,
}
export interface ClientInput {
  'websiteUrl' : Url,
  'sortOrder' : bigint,
  'name' : string,
  'logoUrl' : Url,
}
export interface ContactInput {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface ContactSubmission {
  'id' : Id,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface FaqInput {
  'question' : string,
  'sortOrder' : bigint,
  'answer' : string,
}
export interface FaqItem {
  'id' : Id,
  'question' : string,
  'sortOrder' : bigint,
  'answer' : string,
}
export interface HeroContent {
  'subheading' : string,
  'headline' : string,
  'ctaLink' : string,
  'secondaryCtaLink' : string,
  'ctaText' : string,
  'secondaryCtaText' : string,
}
export type Id = bigint;
export interface Industry {
  'id' : Id,
  'title' : string,
  'sortOrder' : bigint,
  'description' : string,
  'iconName' : string,
}
export interface IndustryInput {
  'title' : string,
  'sortOrder' : bigint,
  'description' : string,
  'iconName' : string,
}
export interface Partner {
  'id' : Id,
  'websiteUrl' : Url,
  'sortOrder' : bigint,
  'name' : string,
  'description' : string,
  'logoUrl' : Url,
}
export interface PartnerInput {
  'websiteUrl' : Url,
  'sortOrder' : bigint,
  'name' : string,
  'description' : string,
  'logoUrl' : Url,
}
export interface PortfolioInput {
  'title' : string,
  'sortOrder' : bigint,
  'link' : Url,
  'tags' : Array<string>,
  'description' : string,
  'imageUrl' : Url,
}
export interface PortfolioItem {
  'id' : Id,
  'title' : string,
  'sortOrder' : bigint,
  'link' : Url,
  'tags' : Array<string>,
  'description' : string,
  'imageUrl' : Url,
}
export interface Shape {
  'id' : Id,
  'title' : string,
  'sortOrder' : bigint,
  'icon' : string,
  'description' : string,
}
export interface ShapeInput {
  'title' : string,
  'sortOrder' : bigint,
  'icon' : string,
  'description' : string,
}
export interface SiteSettings {
  'tagline' : string,
  'socialLinks' : SocialLinks,
  'email' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'companyName' : string,
  'phone' : string,
}
export interface SocialLinks {
  'linkedin' : string,
  'twitter' : string,
  'instagram' : string,
  'facebook' : string,
  'github' : string,
}
export interface Solution {
  'id' : Id,
  'title' : string,
  'features' : Array<string>,
  'sortOrder' : bigint,
  'icon' : string,
  'description' : string,
}
export interface SolutionInput {
  'title' : string,
  'features' : Array<string>,
  'sortOrder' : bigint,
  'icon' : string,
  'description' : string,
}
export interface TeamMember {
  'id' : Id,
  'bio' : string,
  'sortOrder' : bigint,
  'name' : string,
  'role' : string,
  'photoUrl' : Url,
}
export interface TeamMemberInput {
  'bio' : string,
  'sortOrder' : bigint,
  'name' : string,
  'role' : string,
  'photoUrl' : Url,
}
export interface Testimonial {
  'id' : Id,
  'title' : string,
  'sortOrder' : bigint,
  'name' : string,
  'quote' : string,
  'company' : string,
  'rating' : bigint,
}
export interface TestimonialInput {
  'title' : string,
  'sortOrder' : bigint,
  'name' : string,
  'quote' : string,
  'company' : string,
  'rating' : bigint,
}
export type Timestamp = bigint;
export type Url = string;
export interface _SERVICE {
  'addBlogPost' : ActorMethod<[BlogPostInput], AdminResult>,
  'addClient' : ActorMethod<[ClientInput], AdminResult>,
  'addFaqItem' : ActorMethod<[FaqInput], AdminResult>,
  'addIndustry' : ActorMethod<[IndustryInput], AdminResult>,
  'addPartner' : ActorMethod<[PartnerInput], AdminResult>,
  'addPortfolioItem' : ActorMethod<[PortfolioInput], AdminResult>,
  'addShape' : ActorMethod<[ShapeInput], AdminResult>,
  'addSolution' : ActorMethod<[SolutionInput], AdminResult>,
  'addTeamMember' : ActorMethod<[TeamMemberInput], AdminResult>,
  'addTestimonial' : ActorMethod<[TestimonialInput], AdminResult>,
  'deleteBlogPost' : ActorMethod<[Id], AdminResult>,
  'deleteClient' : ActorMethod<[Id], AdminResult>,
  'deleteContactSubmission' : ActorMethod<[Id], AdminResult>,
  'deleteFaqItem' : ActorMethod<[Id], AdminResult>,
  'deleteIndustry' : ActorMethod<[Id], AdminResult>,
  'deletePartner' : ActorMethod<[Id], AdminResult>,
  'deletePortfolioItem' : ActorMethod<[Id], AdminResult>,
  'deleteShape' : ActorMethod<[Id], AdminResult>,
  'deleteSolution' : ActorMethod<[Id], AdminResult>,
  'deleteTeamMember' : ActorMethod<[Id], AdminResult>,
  'deleteTestimonial' : ActorMethod<[Id], AdminResult>,
  'getAbout' : ActorMethod<[], AboutContent>,
  'getAdmin' : ActorMethod<[], Principal>,
  'getBlogPost' : ActorMethod<[Id], [] | [BlogPost]>,
  'getBlogPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getHero' : ActorMethod<[], HeroContent>,
  'getSettings' : ActorMethod<[], SiteSettings>,
  'listBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listClients' : ActorMethod<[], Array<Client>>,
  'listContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'listFaq' : ActorMethod<[], Array<FaqItem>>,
  'listIndustries' : ActorMethod<[], Array<Industry>>,
  'listPartners' : ActorMethod<[], Array<Partner>>,
  'listPortfolio' : ActorMethod<[], Array<PortfolioItem>>,
  'listPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listShapes' : ActorMethod<[], Array<Shape>>,
  'listSolutions' : ActorMethod<[], Array<Solution>>,
  'listTeam' : ActorMethod<[], Array<TeamMember>>,
  'listTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'setAdmin' : ActorMethod<[Principal], AdminResult>,
  'submitContact' : ActorMethod<[ContactInput], boolean>,
  'updateAbout' : ActorMethod<[AboutContent], AdminResult>,
  'updateBlogPost' : ActorMethod<[Id, BlogPostInput], AdminResult>,
  'updateClient' : ActorMethod<[Id, ClientInput], AdminResult>,
  'updateFaqItem' : ActorMethod<[Id, FaqInput], AdminResult>,
  'updateHero' : ActorMethod<[HeroContent], AdminResult>,
  'updateIndustry' : ActorMethod<[Id, IndustryInput], AdminResult>,
  'updatePartner' : ActorMethod<[Id, PartnerInput], AdminResult>,
  'updatePortfolioItem' : ActorMethod<[Id, PortfolioInput], AdminResult>,
  'updateSettings' : ActorMethod<[SiteSettings], AdminResult>,
  'updateShape' : ActorMethod<[Id, ShapeInput], AdminResult>,
  'updateSolution' : ActorMethod<[Id, SolutionInput], AdminResult>,
  'updateTeamMember' : ActorMethod<[Id, TeamMemberInput], AdminResult>,
  'updateTestimonial' : ActorMethod<[Id, TestimonialInput], AdminResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];