/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const BlogPostInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Timestamp,
  'published' : IDL.Bool,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'summary' : IDL.Text,
});
export const AdminResult = IDL.Variant({
  'ok' : IDL.Null,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const Url = IDL.Text;
export const ClientInput = IDL.Record({
  'websiteUrl' : Url,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'logoUrl' : Url,
});
export const FaqInput = IDL.Record({
  'question' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'answer' : IDL.Text,
});
export const IndustryInput = IDL.Record({
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
});
export const PartnerInput = IDL.Record({
  'websiteUrl' : Url,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : Url,
});
export const PortfolioInput = IDL.Record({
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'link' : Url,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : Url,
});
export const ShapeInput = IDL.Record({
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const SolutionInput = IDL.Record({
  'title' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'sortOrder' : IDL.Nat,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const TeamMemberInput = IDL.Record({
  'bio' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'photoUrl' : Url,
});
export const TestimonialInput = IDL.Record({
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'quote' : IDL.Text,
  'company' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Id = IDL.Nat;
export const AboutContent = IDL.Record({
  'mission' : IDL.Text,
  'description' : IDL.Text,
  'vision' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Timestamp,
  'published' : IDL.Bool,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'summary' : IDL.Text,
});
export const HeroContent = IDL.Record({
  'subheading' : IDL.Text,
  'headline' : IDL.Text,
  'ctaLink' : IDL.Text,
  'secondaryCtaLink' : IDL.Text,
  'ctaText' : IDL.Text,
  'secondaryCtaText' : IDL.Text,
});
export const SocialLinks = IDL.Record({
  'linkedin' : IDL.Text,
  'twitter' : IDL.Text,
  'instagram' : IDL.Text,
  'facebook' : IDL.Text,
  'github' : IDL.Text,
});
export const SiteSettings = IDL.Record({
  'tagline' : IDL.Text,
  'socialLinks' : SocialLinks,
  'email' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const Client = IDL.Record({
  'id' : Id,
  'websiteUrl' : Url,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'logoUrl' : Url,
});
export const ContactSubmission = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const FaqItem = IDL.Record({
  'id' : Id,
  'question' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'answer' : IDL.Text,
});
export const Industry = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
});
export const Partner = IDL.Record({
  'id' : Id,
  'websiteUrl' : Url,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : Url,
});
export const PortfolioItem = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'link' : Url,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : Url,
});
export const Shape = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const Solution = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'sortOrder' : IDL.Nat,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'id' : Id,
  'bio' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'photoUrl' : Url,
});
export const Testimonial = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'quote' : IDL.Text,
  'company' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ContactInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func([BlogPostInput], [AdminResult], []),
  'addClient' : IDL.Func([ClientInput], [AdminResult], []),
  'addFaqItem' : IDL.Func([FaqInput], [AdminResult], []),
  'addIndustry' : IDL.Func([IndustryInput], [AdminResult], []),
  'addPartner' : IDL.Func([PartnerInput], [AdminResult], []),
  'addPortfolioItem' : IDL.Func([PortfolioInput], [AdminResult], []),
  'addShape' : IDL.Func([ShapeInput], [AdminResult], []),
  'addSolution' : IDL.Func([SolutionInput], [AdminResult], []),
  'addTeamMember' : IDL.Func([TeamMemberInput], [AdminResult], []),
  'addTestimonial' : IDL.Func([TestimonialInput], [AdminResult], []),
  'deleteBlogPost' : IDL.Func([Id], [AdminResult], []),
  'deleteClient' : IDL.Func([Id], [AdminResult], []),
  'deleteContactSubmission' : IDL.Func([Id], [AdminResult], []),
  'deleteFaqItem' : IDL.Func([Id], [AdminResult], []),
  'deleteIndustry' : IDL.Func([Id], [AdminResult], []),
  'deletePartner' : IDL.Func([Id], [AdminResult], []),
  'deletePortfolioItem' : IDL.Func([Id], [AdminResult], []),
  'deleteShape' : IDL.Func([Id], [AdminResult], []),
  'deleteSolution' : IDL.Func([Id], [AdminResult], []),
  'deleteTeamMember' : IDL.Func([Id], [AdminResult], []),
  'deleteTestimonial' : IDL.Func([Id], [AdminResult], []),
  'getAbout' : IDL.Func([], [AboutContent], ['query']),
  'getAdmin' : IDL.Func([], [IDL.Principal], ['query']),
  'getBlogPost' : IDL.Func([Id], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getHero' : IDL.Func([], [HeroContent], ['query']),
  'getSettings' : IDL.Func([], [SiteSettings], ['query']),
  'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'listContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
  'listFaq' : IDL.Func([], [IDL.Vec(FaqItem)], ['query']),
  'listIndustries' : IDL.Func([], [IDL.Vec(Industry)], ['query']),
  'listPartners' : IDL.Func([], [IDL.Vec(Partner)], ['query']),
  'listPortfolio' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'listPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listShapes' : IDL.Func([], [IDL.Vec(Shape)], ['query']),
  'listSolutions' : IDL.Func([], [IDL.Vec(Solution)], ['query']),
  'listTeam' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'setAdmin' : IDL.Func([IDL.Principal], [AdminResult], []),
  'submitContact' : IDL.Func([ContactInput], [IDL.Bool], []),
  'updateAbout' : IDL.Func([AboutContent], [AdminResult], []),
  'updateBlogPost' : IDL.Func([Id, BlogPostInput], [AdminResult], []),
  'updateClient' : IDL.Func([Id, ClientInput], [AdminResult], []),
  'updateFaqItem' : IDL.Func([Id, FaqInput], [AdminResult], []),
  'updateHero' : IDL.Func([HeroContent], [AdminResult], []),
  'updateIndustry' : IDL.Func([Id, IndustryInput], [AdminResult], []),
  'updatePartner' : IDL.Func([Id, PartnerInput], [AdminResult], []),
  'updatePortfolioItem' : IDL.Func([Id, PortfolioInput], [AdminResult], []),
  'updateSettings' : IDL.Func([SiteSettings], [AdminResult], []),
  'updateShape' : IDL.Func([Id, ShapeInput], [AdminResult], []),
  'updateSolution' : IDL.Func([Id, SolutionInput], [AdminResult], []),
  'updateTeamMember' : IDL.Func([Id, TeamMemberInput], [AdminResult], []),
  'updateTestimonial' : IDL.Func([Id, TestimonialInput], [AdminResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const BlogPostInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Timestamp,
    'published' : IDL.Bool,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'summary' : IDL.Text,
  });
  const AdminResult = IDL.Variant({
    'ok' : IDL.Null,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const Url = IDL.Text;
  const ClientInput = IDL.Record({
    'websiteUrl' : Url,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'logoUrl' : Url,
  });
  const FaqInput = IDL.Record({
    'question' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'answer' : IDL.Text,
  });
  const IndustryInput = IDL.Record({
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
  });
  const PartnerInput = IDL.Record({
    'websiteUrl' : Url,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : Url,
  });
  const PortfolioInput = IDL.Record({
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'link' : Url,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : Url,
  });
  const ShapeInput = IDL.Record({
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const SolutionInput = IDL.Record({
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'sortOrder' : IDL.Nat,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const TeamMemberInput = IDL.Record({
    'bio' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'photoUrl' : Url,
  });
  const TestimonialInput = IDL.Record({
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'quote' : IDL.Text,
    'company' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Id = IDL.Nat;
  const AboutContent = IDL.Record({
    'mission' : IDL.Text,
    'description' : IDL.Text,
    'vision' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Timestamp,
    'published' : IDL.Bool,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'summary' : IDL.Text,
  });
  const HeroContent = IDL.Record({
    'subheading' : IDL.Text,
    'headline' : IDL.Text,
    'ctaLink' : IDL.Text,
    'secondaryCtaLink' : IDL.Text,
    'ctaText' : IDL.Text,
    'secondaryCtaText' : IDL.Text,
  });
  const SocialLinks = IDL.Record({
    'linkedin' : IDL.Text,
    'twitter' : IDL.Text,
    'instagram' : IDL.Text,
    'facebook' : IDL.Text,
    'github' : IDL.Text,
  });
  const SiteSettings = IDL.Record({
    'tagline' : IDL.Text,
    'socialLinks' : SocialLinks,
    'email' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Client = IDL.Record({
    'id' : Id,
    'websiteUrl' : Url,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'logoUrl' : Url,
  });
  const ContactSubmission = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const FaqItem = IDL.Record({
    'id' : Id,
    'question' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'answer' : IDL.Text,
  });
  const Industry = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
  });
  const Partner = IDL.Record({
    'id' : Id,
    'websiteUrl' : Url,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : Url,
  });
  const PortfolioItem = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'link' : Url,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : Url,
  });
  const Shape = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const Solution = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'sortOrder' : IDL.Nat,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'id' : Id,
    'bio' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'photoUrl' : Url,
  });
  const Testimonial = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'quote' : IDL.Text,
    'company' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ContactInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func([BlogPostInput], [AdminResult], []),
    'addClient' : IDL.Func([ClientInput], [AdminResult], []),
    'addFaqItem' : IDL.Func([FaqInput], [AdminResult], []),
    'addIndustry' : IDL.Func([IndustryInput], [AdminResult], []),
    'addPartner' : IDL.Func([PartnerInput], [AdminResult], []),
    'addPortfolioItem' : IDL.Func([PortfolioInput], [AdminResult], []),
    'addShape' : IDL.Func([ShapeInput], [AdminResult], []),
    'addSolution' : IDL.Func([SolutionInput], [AdminResult], []),
    'addTeamMember' : IDL.Func([TeamMemberInput], [AdminResult], []),
    'addTestimonial' : IDL.Func([TestimonialInput], [AdminResult], []),
    'deleteBlogPost' : IDL.Func([Id], [AdminResult], []),
    'deleteClient' : IDL.Func([Id], [AdminResult], []),
    'deleteContactSubmission' : IDL.Func([Id], [AdminResult], []),
    'deleteFaqItem' : IDL.Func([Id], [AdminResult], []),
    'deleteIndustry' : IDL.Func([Id], [AdminResult], []),
    'deletePartner' : IDL.Func([Id], [AdminResult], []),
    'deletePortfolioItem' : IDL.Func([Id], [AdminResult], []),
    'deleteShape' : IDL.Func([Id], [AdminResult], []),
    'deleteSolution' : IDL.Func([Id], [AdminResult], []),
    'deleteTeamMember' : IDL.Func([Id], [AdminResult], []),
    'deleteTestimonial' : IDL.Func([Id], [AdminResult], []),
    'getAbout' : IDL.Func([], [AboutContent], ['query']),
    'getAdmin' : IDL.Func([], [IDL.Principal], ['query']),
    'getBlogPost' : IDL.Func([Id], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getHero' : IDL.Func([], [HeroContent], ['query']),
    'getSettings' : IDL.Func([], [SiteSettings], ['query']),
    'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'listContactSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
    'listFaq' : IDL.Func([], [IDL.Vec(FaqItem)], ['query']),
    'listIndustries' : IDL.Func([], [IDL.Vec(Industry)], ['query']),
    'listPartners' : IDL.Func([], [IDL.Vec(Partner)], ['query']),
    'listPortfolio' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'listPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listShapes' : IDL.Func([], [IDL.Vec(Shape)], ['query']),
    'listSolutions' : IDL.Func([], [IDL.Vec(Solution)], ['query']),
    'listTeam' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'setAdmin' : IDL.Func([IDL.Principal], [AdminResult], []),
    'submitContact' : IDL.Func([ContactInput], [IDL.Bool], []),
    'updateAbout' : IDL.Func([AboutContent], [AdminResult], []),
    'updateBlogPost' : IDL.Func([Id, BlogPostInput], [AdminResult], []),
    'updateClient' : IDL.Func([Id, ClientInput], [AdminResult], []),
    'updateFaqItem' : IDL.Func([Id, FaqInput], [AdminResult], []),
    'updateHero' : IDL.Func([HeroContent], [AdminResult], []),
    'updateIndustry' : IDL.Func([Id, IndustryInput], [AdminResult], []),
    'updatePartner' : IDL.Func([Id, PartnerInput], [AdminResult], []),
    'updatePortfolioItem' : IDL.Func([Id, PortfolioInput], [AdminResult], []),
    'updateSettings' : IDL.Func([SiteSettings], [AdminResult], []),
    'updateShape' : IDL.Func([Id, ShapeInput], [AdminResult], []),
    'updateSolution' : IDL.Func([Id, SolutionInput], [AdminResult], []),
    'updateTeamMember' : IDL.Func([Id, TeamMemberInput], [AdminResult], []),
    'updateTestimonial' : IDL.Func([Id, TestimonialInput], [AdminResult], []),
  });
};

export const init = ({ IDL }) => { return []; };