/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PartnerInput {
    websiteUrl: Url;
    sortOrder: bigint;
    name: string;
    description: string;
    logoUrl: Url;
}
export interface AboutContent {
    mission: string;
    description: string;
    vision: string;
}
export type Timestamp = bigint;
export interface ContactSubmission {
    id: Id;
    name: string;
    email: string;
    message: string;
    timestamp: Timestamp;
}
export interface BlogPostInput {
    title: string;
    content: string;
    date: Timestamp;
    published: boolean;
    slug: string;
    tags: Array<string>;
    author: string;
    summary: string;
}
export interface SocialLinks {
    linkedin: string;
    twitter: string;
    instagram: string;
    facebook: string;
    github: string;
}
export interface FaqInput {
    question: string;
    sortOrder: bigint;
    answer: string;
}
export interface TestimonialInput {
    title: string;
    sortOrder: bigint;
    name: string;
    quote: string;
    company: string;
    rating: bigint;
}
export type Url = string;
export interface SolutionInput {
    title: string;
    features: Array<string>;
    sortOrder: bigint;
    icon: string;
    description: string;
}
export interface Solution {
    id: Id;
    title: string;
    features: Array<string>;
    sortOrder: bigint;
    icon: string;
    description: string;
}
export interface ClientInput {
    websiteUrl: Url;
    sortOrder: bigint;
    name: string;
    logoUrl: Url;
}
export interface TeamMemberInput {
    bio: string;
    sortOrder: bigint;
    name: string;
    role: string;
    photoUrl: Url;
}
export interface Client {
    id: Id;
    websiteUrl: Url;
    sortOrder: bigint;
    name: string;
    logoUrl: Url;
}
export interface PortfolioInput {
    title: string;
    sortOrder: bigint;
    link: Url;
    tags: Array<string>;
    description: string;
    imageUrl: Url;
}
export interface ContactInput {
    name: string;
    email: string;
    message: string;
}
export interface BlogPost {
    id: Id;
    title: string;
    content: string;
    date: Timestamp;
    published: boolean;
    slug: string;
    tags: Array<string>;
    author: string;
    summary: string;
}
export interface IndustryInput {
    title: string;
    sortOrder: bigint;
    description: string;
    iconName: string;
}
export interface HeroContent {
    subheading: string;
    headline: string;
    ctaLink: string;
    secondaryCtaLink: string;
    ctaText: string;
    secondaryCtaText: string;
}
export interface Partner {
    id: Id;
    websiteUrl: Url;
    sortOrder: bigint;
    name: string;
    description: string;
    logoUrl: Url;
}
export interface Shape {
    id: Id;
    title: string;
    sortOrder: bigint;
    icon: string;
    description: string;
}
export interface Industry {
    id: Id;
    title: string;
    sortOrder: bigint;
    description: string;
    iconName: string;
}
export interface ShapeInput {
    title: string;
    sortOrder: bigint;
    icon: string;
    description: string;
}
export interface FaqItem {
    id: Id;
    question: string;
    sortOrder: bigint;
    answer: string;
}
export interface SiteSettings {
    tagline: string;
    socialLinks: SocialLinks;
    email: string;
    addressLine1: string;
    addressLine2: string;
    companyName: string;
    phone: string;
}
export interface PortfolioItem {
    id: Id;
    title: string;
    sortOrder: bigint;
    link: Url;
    tags: Array<string>;
    description: string;
    imageUrl: Url;
}
export type Id = bigint;
export interface TeamMember {
    id: Id;
    bio: string;
    sortOrder: bigint;
    name: string;
    role: string;
    photoUrl: Url;
}
export interface Testimonial {
    id: Id;
    title: string;
    sortOrder: bigint;
    name: string;
    quote: string;
    company: string;
    rating: bigint;
}
export enum AdminResult {
    ok = "ok",
    notFound = "notFound",
    unauthorized = "unauthorized"
}
export interface backendInterface {
    addBlogPost(input: BlogPostInput): Promise<AdminResult>;
    addClient(input: ClientInput): Promise<AdminResult>;
    addFaqItem(input: FaqInput): Promise<AdminResult>;
    addIndustry(input: IndustryInput): Promise<AdminResult>;
    addPartner(input: PartnerInput): Promise<AdminResult>;
    addPortfolioItem(input: PortfolioInput): Promise<AdminResult>;
    addShape(input: ShapeInput): Promise<AdminResult>;
    addSolution(input: SolutionInput): Promise<AdminResult>;
    addTeamMember(input: TeamMemberInput): Promise<AdminResult>;
    addTestimonial(input: TestimonialInput): Promise<AdminResult>;
    deleteBlogPost(id: Id): Promise<AdminResult>;
    deleteClient(id: Id): Promise<AdminResult>;
    deleteContactSubmission(id: Id): Promise<AdminResult>;
    deleteFaqItem(id: Id): Promise<AdminResult>;
    deleteIndustry(id: Id): Promise<AdminResult>;
    deletePartner(id: Id): Promise<AdminResult>;
    deletePortfolioItem(id: Id): Promise<AdminResult>;
    deleteShape(id: Id): Promise<AdminResult>;
    deleteSolution(id: Id): Promise<AdminResult>;
    deleteTeamMember(id: Id): Promise<AdminResult>;
    deleteTestimonial(id: Id): Promise<AdminResult>;
    getAbout(): Promise<AboutContent>;
    getAdmin(): Promise<Principal>;
    getBlogPost(id: Id): Promise<BlogPost | null>;
    getBlogPostBySlug(slug: string): Promise<BlogPost | null>;
    getHero(): Promise<HeroContent>;
    getSettings(): Promise<SiteSettings>;
    listBlogPosts(): Promise<Array<BlogPost>>;
    listClients(): Promise<Array<Client>>;
    listContactSubmissions(): Promise<Array<ContactSubmission>>;
    listFaq(): Promise<Array<FaqItem>>;
    listIndustries(): Promise<Array<Industry>>;
    listPartners(): Promise<Array<Partner>>;
    listPortfolio(): Promise<Array<PortfolioItem>>;
    listPublishedBlogPosts(): Promise<Array<BlogPost>>;
    listShapes(): Promise<Array<Shape>>;
    listSolutions(): Promise<Array<Solution>>;
    listTeam(): Promise<Array<TeamMember>>;
    listTestimonials(): Promise<Array<Testimonial>>;
    setAdmin(newAdmin: Principal): Promise<AdminResult>;
    submitContact(input: ContactInput): Promise<boolean>;
    updateAbout(input: AboutContent): Promise<AdminResult>;
    updateBlogPost(id: Id, input: BlogPostInput): Promise<AdminResult>;
    updateClient(id: Id, input: ClientInput): Promise<AdminResult>;
    updateFaqItem(id: Id, input: FaqInput): Promise<AdminResult>;
    updateHero(input: HeroContent): Promise<AdminResult>;
    updateIndustry(id: Id, input: IndustryInput): Promise<AdminResult>;
    updatePartner(id: Id, input: PartnerInput): Promise<AdminResult>;
    updatePortfolioItem(id: Id, input: PortfolioInput): Promise<AdminResult>;
    updateSettings(input: SiteSettings): Promise<AdminResult>;
    updateShape(id: Id, input: ShapeInput): Promise<AdminResult>;
    updateSolution(id: Id, input: SolutionInput): Promise<AdminResult>;
    updateTeamMember(id: Id, input: TeamMemberInput): Promise<AdminResult>;
    updateTestimonial(id: Id, input: TestimonialInput): Promise<AdminResult>;
}
import type { AdminResult as _AdminResult, BlogPost as _BlogPost } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBlogPost(arg0: BlogPostInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addClient(arg0: ClientInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addClient(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClient(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addFaqItem(arg0: FaqInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addFaqItem(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFaqItem(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addIndustry(arg0: IndustryInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addIndustry(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIndustry(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPartner(arg0: PartnerInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addPartner(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPartner(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPortfolioItem(arg0: PortfolioInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addPortfolioItem(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPortfolioItem(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addShape(arg0: ShapeInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addShape(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShape(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addSolution(arg0: SolutionInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addSolution(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSolution(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTeamMember(arg0: TeamMemberInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeamMember(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeamMember(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTestimonial(arg0: TestimonialInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBlogPost(arg0: Id): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteClient(arg0: Id): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteContactSubmission(arg0: Id): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactSubmission(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactSubmission(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFaqItem(arg0: Id): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFaqItem(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFaqItem(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteIndustry(arg0: Id): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIndustry(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIndustry(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePartner(arg0: Id): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePartner(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePartner(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePortfolioItem(arg0: Id): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePortfolioItem(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePortfolioItem(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteShape(arg0: Id): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShape(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShape(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteSolution(arg0: Id): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSolution(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSolution(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTeamMember(arg0: Id): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeamMember(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeamMember(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTestimonial(arg0: Id): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAbout(): Promise<AboutContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getAbout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAbout();
            return result;
        }
    }
    async getAdmin(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmin();
            return result;
        }
    }
    async getBlogPost(arg0: Id): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostBySlug(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostBySlug(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostBySlug(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHero(): Promise<HeroContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getHero();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHero();
            return result;
        }
    }
    async getSettings(): Promise<SiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async listBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBlogPosts();
            return result;
        }
    }
    async listClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClients();
            return result;
        }
    }
    async listContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContactSubmissions();
            return result;
        }
    }
    async listFaq(): Promise<Array<FaqItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFaq();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFaq();
            return result;
        }
    }
    async listIndustries(): Promise<Array<Industry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listIndustries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listIndustries();
            return result;
        }
    }
    async listPartners(): Promise<Array<Partner>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPartners();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPartners();
            return result;
        }
    }
    async listPortfolio(): Promise<Array<PortfolioItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPortfolio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPortfolio();
            return result;
        }
    }
    async listPublishedBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublishedBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublishedBlogPosts();
            return result;
        }
    }
    async listShapes(): Promise<Array<Shape>> {
        if (this.processError) {
            try {
                const result = await this.actor.listShapes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listShapes();
            return result;
        }
    }
    async listSolutions(): Promise<Array<Solution>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSolutions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSolutions();
            return result;
        }
    }
    async listTeam(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeam();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeam();
            return result;
        }
    }
    async listTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTestimonials();
            return result;
        }
    }
    async setAdmin(arg0: Principal): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContact(arg0: ContactInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0);
            return result;
        }
    }
    async updateAbout(arg0: AboutContent): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAbout(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAbout(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBlogPost(arg0: Id, arg1: BlogPostInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClient(arg0: Id, arg1: ClientInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFaqItem(arg0: Id, arg1: FaqInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFaqItem(arg0, arg1);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFaqItem(arg0, arg1);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateHero(arg0: HeroContent): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHero(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHero(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateIndustry(arg0: Id, arg1: IndustryInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIndustry(arg0, arg1);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIndustry(arg0, arg1);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePartner(arg0: Id, arg1: PartnerInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePartner(arg0, arg1);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePartner(arg0, arg1);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePortfolioItem(arg0: Id, arg1: PortfolioInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePortfolioItem(arg0, arg1);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePortfolioItem(arg0, arg1);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: SiteSettings): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateShape(arg0: Id, arg1: ShapeInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShape(arg0, arg1);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShape(arg0, arg1);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSolution(arg0: Id, arg1: SolutionInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSolution(arg0, arg1);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSolution(arg0, arg1);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTeamMember(arg0: Id, arg1: TeamMemberInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamMember(arg0, arg1);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamMember(arg0, arg1);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTestimonial(arg0: Id, arg1: TestimonialInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonial(arg0, arg1);
                return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonial(arg0, arg1);
            return from_candid_AdminResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminResult): AdminResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notFound: null;
} | {
    unauthorized: null;
}): AdminResult {
    return "ok" in value ? AdminResult.ok : "notFound" in value ? AdminResult.notFound : "unauthorized" in value ? AdminResult.unauthorized : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
